/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projek_akhirrr;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

public class updateJanjiTemu extends javax.swing.JFrame {

    Connection konek;
    DefaultTableModel modelJanjiTemu;
    DefaultComboBoxModel modelCmbID;
    
    public updateJanjiTemu() {
        initComponents();
        konek = koneksi.getConnection();
       
        modelCmbID = new DefaultComboBoxModel();
        cmb_id.setModel(modelCmbID);
        
        modelJanjiTemu = new DefaultTableModel();
        
        modelJanjiTemu.addColumn("ID");
        modelJanjiTemu.addColumn("Id Pasien");
        modelJanjiTemu.addColumn("Nama Pasien");
        modelJanjiTemu.addColumn("Id Dokter");
        modelJanjiTemu.addColumn("Nama Dokter");
        modelJanjiTemu.addColumn("Tanggal");
        modelJanjiTemu.addColumn("Jam");
        modelJanjiTemu.addColumn("Status");
        modelJanjiTemu.addColumn("Diagnosa");
        modelJanjiTemu.addColumn("Obat");
        tb_janji_temu.setModel(modelJanjiTemu);
        
        loadDataId();
        loadDataJanjiTemu();
    }
    
    private void loadDataId(){
    modelCmbID.removeAllElements();
    
    try{
        String query = "SELECT id FROM janji_temu";
        PreparedStatement ps = konek.prepareStatement(query);
        ResultSet rs = ps.executeQuery();
        while(rs.next()){
        String data = rs.getString("id");
        modelCmbID.addElement(data);
        }        
    }catch(SQLException e){
        System.out.println("Fail "+ e.getMessage());
    }
    cmb_id.setModel(modelCmbID);
    }
        
    private void loadDataJanjiTemu(){
    modelJanjiTemu.setRowCount(0);
    
    try {
        String query = "SELECT jt.id,jt.jam, jt.id_pasien, p.nama AS nama_pasien, jt.id_dokter, d.nama AS nama_dokter, " +
                       "jt.tanggal, jt.status, jt.diagnosa, jt.obat " +
                       "FROM janji_temu jt " +
                       "JOIN pasien p ON jt.id_pasien = p.id " +
                       "JOIN dokter d ON jt.id_dokter = d.id";
                       
        PreparedStatement ps = konek.prepareStatement(query);
        ResultSet rs = ps.executeQuery();
        
        while(rs.next()) {
            modelJanjiTemu.addRow(new Object[]{
                rs.getInt("id"),
                rs.getInt("id_pasien"),
                rs.getString("nama_pasien"),
                rs.getInt("id_dokter"),        
                rs.getString("nama_dokter"),
                rs.getString("tanggal"),
                rs.getString("jam"),
                rs.getString("status"),
                rs.getString("diagnosa"),
                rs.getString("obat")
            });
        }
    } catch(SQLException e) {
        System.out.println("Fail " + e.getMessage());
    }
    }
    private void updateJanjiTemu(){
        
        try{
            
            String query = "UPDATE janji_temu SET status = ?,diagnosa= ?,obat=? WHERE id=?";
            PreparedStatement ps = konek.prepareStatement(query);

            ps.setString(1, cmb_status.getSelectedItem().toString());
            ps.setString(2,tf_diagnosa.getText().trim() );
            ps.setString(3, tf_obat.getText().trim());
            ps.setInt(4,Integer.parseInt(cmb_id.getSelectedItem().toString()));
            ps.execute();
            
            JOptionPane.showMessageDialog(this,"Data Berhasil diupdate!!","INFO wak",JOptionPane.INFORMATION_MESSAGE);
            loadDataJanjiTemu();
            
        }catch(SQLException e){
            System.out.println("Fail " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_janji_temu = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmb_status = new javax.swing.JComboBox<>();
        tf_diagnosa = new javax.swing.JTextField();
        tf_obat = new javax.swing.JTextField();
        btn_update = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cmb_id = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_janji_temu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_janji_temu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 800, 240));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Status");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Diagnosa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Obat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel6, gridBagConstraints);

        cmb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sudah Bertemu", "Belum Bertemu" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(cmb_status, gridBagConstraints);

        tf_diagnosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_diagnosaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(tf_diagnosa, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(tf_obat, gridBagConstraints);

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel1.add(btn_update, gridBagConstraints);

        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel1.add(btn_keluar, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel7, gridBagConstraints);

        cmb_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(cmb_id, gridBagConstraints);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 280, 170));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Update Janji Temu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Downloads\\Healthcare-Featured-Image (1) (1).png")); // NOI18N
        jLabel1.setText("a");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_diagnosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_diagnosaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_diagnosaActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        if(tf_diagnosa.getText().trim().isEmpty()||tf_obat.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"","",JOptionPane.INFORMATION_MESSAGE);
        }else{
            updateJanjiTemu();
        }    
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        main main = new main();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cmb_id;
    private javax.swing.JComboBox<String> cmb_status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_janji_temu;
    private javax.swing.JTextField tf_diagnosa;
    private javax.swing.JTextField tf_obat;
    // End of variables declaration//GEN-END:variables
}
